joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

taymay1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: taymay1_joint
  pid: {p: 3.0, i: 0.01, d: 0.1}
  initial_position: 0.0

taymay2_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: taymay2_joint
  pid: {p: 3.0, i: 0.01, d: 0.1}
  initial_position: 0.0
